### ISSUE TITLE
Host on GitHub pages?

### ISSUE THREAD

**Issue by svm1** [CloudCannon/fur-jekyll-template#6]
Might be a silly question, but could this site be hosted using GitHub Pages?

**Comment by donaldboulton** [comment]
Fork it clone it, set up _config.yml and done.
It works at[My Fork](https://donaldboulton.github.io/fur-jekyll-template/)

**Comment by ahmadihamid** [comment]
> Fork it clone it, set up _config.yml and done.
> It works at[My Fork](https://donaldboulton.github.io/fur-jekyll-template/)

product links are all broken, tried this and see the same problem. 

anyone know how to fix this?

**Comment by donaldboulton** [comment]
Rebuilt at my repo [Works on local host](https://github.com/donaldboulton/fur-jekyll-template).
Still the relative URLs are messed up on github, cloudcannon had some old Jekyll stuff that would not work correctly. Removed ther url filter and changed the css and js links to work.
_config.yml was not correct, no plugins or correct collections = fixed.
Had the same relative url problem on all of my Github sites using github hosting with no cname and my own domain name. You all will have to figure that one out., my repo works on Netlify = try netlify its free and the best for static sites or figure out the relative url issue with gh-pages, this being on master not gh-pages might be the issue also.
I have other repos to fix so I will not do any more to this, its now correct and is working on a real server.
